-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE * t2.COUNT) AS SALES FROM PRODUCT AS t1
JOIN 
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS COUNT FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS t2 ON t1.PRODUCT_ID = t2.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;