-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME FROM ANIMAL_OUTS AS AO2
WHERE ANIMAL_ID NOT IN 
(
    SELECT AI.ANIMAL_ID
    FROM ANIMAL_INS AS AI
    JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
)
ORDER BY ANIMAL_ID;