-- 코드를 입력하세요

SELECT CONCAT('/home/grep/src/', t2.BOARD_ID, '/', t2.FILE_ID, t2.FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS t2
WHERE (t2.BOARD_ID) = (SELECT BOARD_ID FROM USED_GOODS_BOARD AS t1 ORDER BY VIEWS DESC LIMIT 1) 
ORDER BY t2.FILE_ID DESC;